server:
  port: 8081
  tomcat:
    max-http-form-post-size: 1MB
    max-swallow-size: 1MB

spring:
  application:
    name: auth-service
  config:
    import: optional:file:.env[.properties],optional:file:services/auth-service/.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}
