services:
  redis:
    image: redis:8.2.7
    container_name: "redis"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "6379:6379"

  atlasauthservice:
    image: "sumanydv/atlas-auth-service:v1"
    container_name: "atlas-auth-service"
    ports:
      - "8090:8090"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - ../services/auth-service/.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

networks:
  atlas-network:
    driver: bridge