services:
  redis:
    image: redis:8.2.7
    container_name: "redis"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "6379:6379"
    extends:
      file: common-config.yml
      service: network-deploy-service

  atlasauthservice:
    image: "sumanydv/atlas-auth-service:v2"
    container_name: "atlas-auth-service"
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - ../services/auth-service/.env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    extends:
      file: common-config.yml
      service: microservice-base-config

  workspaceservice:
    image: "sumanydv/atlas-workspace-service:v2"
    container_name: "atlas-workspace-service"
    ports:
      - "9000:9000"
    depends_on:
      atlasauthservice:
        condition: service_healthy
    env_file:
      - ../services/workspace-service/.env
    extends:
      file: common-config.yml
      service: microservice-base-config



networks:
  atlas-network:
    driver: bridge
